on: [push]

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build project with Maven
        run: mvn clean install

      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: "test"
          path: "."
          format: "HTML"
          out: "reports" # this is the default, no need to specify unless you wish to override it
          args: >
            --enableRetired

      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: Depcheck report
          path: ${{github.workspace}}/reports
  
  GenSBOM:
    runs-on: ubuntu-latest
    name: generate_SBOM
    needs:
      - depchecktest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Generate SBOM
        run: mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom
      
      - name: Upload SBOM results
        uses: actions/upload-artifact@master
        with:
          name: SBOM
          path: target/bom.xml
  
  BuildDockerImage:
    runs-on: ubuntu-latest
    name: build docker BuildDockerImage
    needs:
      - GenSBOM
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: dcokerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: build with maven
        run: mvn clean install
      
      - name: build docker image and push to dockerHub
        uses: docker/build-push-action@v5
        with:
            context: .
            push: true
            tags: bo0725/DevSecOps-java-img:latest